<div class="row">
    <div class="col-xs-12">
        <?php   //var_dump($block->getParam()); die;
                $params = $block->getParam();
                if(array_key_exists('valid_cc',$params)){
                    $invalidCcNumber = true;
                } elseif (array_key_exists('valid_date',$params)) {
                    $invalidCcDate = true;
                } elseif (array_key_exists('valid_cvc',$params)) {
                    $invalidCcCvc = true;
                }
                $paymentType = $block->getPaymentType();
                if($paymentType == 2) {
                    $url = $block->getDirectPaymentUrl();
                } elseif($paymentType == 1) {
                    if ($block->isTestMode()) {
                        $url = 'https://ipgtest.' . $block->getProcesor() . '/v2/form';
                    } else {
                        $url = 'https://ipg.' . $block->getProcesor() . '/v2/form';
                    }
                }
        ?>
        <form action="<?php echo $url ?>" method="post" id="redirectpay" class="checkout">
            <?php foreach ($params as $key => $value):
                if($value == '') continue;
            ?>
            <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>" />
            <?php endforeach; ?>

            <?php if($paymentType == 2): ?>
                <div class="checkout-header">
                    <div class="checkout-title">
                        Unesite podatke kreditne kartice
                    </div>
                </div>
            <?php if(isset($invalidCcNumber)): ?>
                <p class="error">
                    Pogrešan broj kartice!
                </p>
            <?php endif; ?>
            <?php if(isset($invalidCcDate)): ?>
                <p class="error">
                    Pogrešan datum isteka kartice!
                </p>
            <?php endif; ?>
            <?php if(isset($invalidCcCvc)): ?>
                <p class="error">
                    Pogrešan cvv broj!
                </p>
            <?php endif; ?>
                <div class="errors">
                    <div class="error-card" id="card-error" style="display: none;">
                        <p class="error">
                            Pogrešan broj kartice!
                        </p>
                    </div>
                    <div class="error-pan" id="pan-error" style="width: 50%;float: left;"></div>
                    <div class="error-cvv" id="cvv-error" style="width: 50%;float: right;text-align: right;"></div>
                </div>
                <p>
                    <input id="pan"
                           class="checkout-input checkout-card"
                           type="text"
                           name='pan'
                           maxlength="19"
                           autocomplete="off"
                           placeholder="Broj kartice"
                           value="<?php if(isset($block->getPostParams()['pan'])) { echo $block->getPostParams()['pan']; } else echo ''; ?>"
                           >
                    <input id="cvv"
                           class="checkout-input checkout-cvc"
                           type="text"
                           name='cvv'
                           maxlength="3"
                           autocomplete="off"
                           placeholder="Cvv"
                           value="<?php if(isset($block->getPostParams()['cvv'])) { echo $block->getPostParams()['cvv']; } else echo ''; ?>"
                           >
                </p>
                <div class="errors">
                    <div class="error-month" id="month-error" style="width: 50%;float: left;"></div>
                    <div class="error-year" id="year-error" style="width: 50%;float: right;text-align: right;"></div>
                </div>
                <p>
                    <select class="checkout-input checkout-exp-mm" id="month" name='month' required>
                        <option selected disabled value="">Mjesec</option>
                        <?php for ($i=1; $i <= 12; $i++) {
                            if(strlen($i) == 1) {
                                $i = '0'.$i;
                            }
                            $tag = '';
                            if(isset($block->getPostParams()['month'])) {
                                if((int)$i == (int)$block->getPostParams()['month']) {
                                    $tag = 'selected';
                                }
                            }
                            echo '<option '.$tag.' value="'.$i.'">'.$i.'</option>';
                        } ?>
                    </select>
                    <select class="checkout-input checkout-exp-yy" id="year" name='year' required>
                        <option selected disabled value="">Godina</option>
                        <?php for ($i=date('Y'); $i <= (date('Y')+10); $i++) {
                            $tag = '';
                            if(isset($block->getPostParams()['year'])) {
                                if((int)substr($i, -2) == (int)$block->getPostParams()['year']) {
                                    $tag = 'selected';
                                }
                            }
                            echo '<option '.$tag.' value="'.substr($i, -2).'">'.$i.'</option>';
                        } ?>
                    </select>
                </p>

                <?php if($block->canPayInInstallments()): ?>
                    <div class="pikpay_installments" style="display:none;">
                        <p>
                        <select name="number_of_installments" class="checkout-input checkout-name">
                            <option value="">Bez rata</option>
                            <?php foreach ($block->getInstallmentsNumber() as $number) {
                                $tag = '';
                                if(isset($block->getPostParams()['number_of_installments'])) {
                                    if((int)$number == (int)$block->getPostParams()['number_of_installments']) {
                                        $tag = 'selected';
                                    }
                                }
                                if(substr($number,-1) == '2' || substr($number,-1) == '3' || substr($number,-1) == '4'){
                                    $text = 'rate';
                                    if (strpos($number, '12') !== false || strpos($number, '13') !== false || strpos($number, '14') !== false) {
                                        $text = 'rata';
                                    }
                                } else $text = 'rata';
                                echo '<option '.$tag.' value="'.$number.'">'.$number.' '.$text.'</option>';
                            } ?>
                        </select>
                        </p>
                    </div>
                <?php endif ?>

                <script type="text/javascript">
                    require(['jquery','mage/mage'],function($) {
                        var dataForm = $('#redirectpay');
                        dataForm.mage('validation', {
                            errorPlacement: function (error, element) {
                                if(element.is('#pan')) {
                                    error.appendTo('#pan-error');
                                } else if (element.is('#cvv')) {
                                    error.appendTo('#cvv-error');
                                } else if(element.is('#month')) {
                                    error.appendTo('#month-error');
                                } else if(element.is('#year')) {
                                    error.appendTo('#year-error');
                                }
                                else {
                                    element.after(error);
                                }
                            },
                            'rules': {
                                'pan': {
                                    'required': true
                                },
                                'cvv': {
                                    'required': true,
                                    'minlength': 3
                                },
                                'month': {
                                    'required': true
                                },
                                'year': {
                                    'required': true
                                }
                            },
                            'messages': {
                                'pan': "Obavezno polje!",
                                'month': "Obavezno polje!",
                                'year': "Obavezno polje!",
                                'cvv': {
                                    "required": "Obavezno polje!",
                                    "minlength": "Morate unijeti 3 broja"
                                }
                            }
                        });
                        $(document).ready(function ($) {
                            var pan = $('#pan');
                            var cvv = $('#cvv');
                            var installments = $('.pikpay_installments');
                            pan.on('change keyup', function () {
                                var sanitized = $(this).val().replace(/[^0-9]/g, '');
                                $(this).val(sanitized);
                            });
                            $('.checkout-btn').on('click', function() {
                                var valid = valid_credit_card(pan.val());
                                if(!valid) {
                                    $('#card-error').show();
                                } else {
                                    $('#card-error').hide();
                                    $('#redirectpay').submit();

                                }
                                console.log('Validna kartica: ',valid);
                            });
                            cvv.on('change keyup', function () {
                                var sanitized = $(this).val().replace(/[^0-9]/g, '');
                                $(this).val(sanitized);
                            });
                            <?php if($block->canPayInInstallments()): ?>
                            pan.on('blur', function () {
                                if (installments.length > 0) {
                                    var ccn = pan.val();
                                    if (ccn != null && ccn.length > 6) {
                                        var cc = ccn.substr(0,6);
                                        var bins = '<?php echo $block->getCcBins() ?>';
                                        if(bins.indexOf(cc) != -1) {
                                            installments.show();
                                        } else installments.hide();
                                    } else installments.hide();
                                }
                            });
                            <?php endif; ?>
                        });
                    });
                </script>
            <?php endif ?>
                <div class="pikpay_submit">
                    <p>
                    <input type="button" value='Plati' class="checkout-btn"/>
                    </p>
                </div>
        </form>
        <div class="col-xs-12">
            <table style="width: 400px; margin: auto;" border="0">
                <tbody>
                <tr>
                    <td>
                        <a href="https://www.visa.com" target="_blank">
                            <img src="<?php echo $this->getViewFileUrl('Leftor_PikPay::images/visa.png') ?>" alt="Visa" />
                        </a>
                    </td>
                    <td>
                        <a href="https://www.visa.com" target="_blank">
                            <img src="<?php echo $this->getViewFileUrl('Leftor_PikPay::images/visa_electron.png') ?>" alt="Visa Electron" />
                        </a>
                    </td>
                    <td>
                        <a href="https://www.mastercard.com" target="_blank">
                            <img src="<?php echo $this->getViewFileUrl('Leftor_PikPay::images/mastercard.png') ?>" alt="MasterCard" />
                        </a>
                    </td>
                    <td>
                        <a href="https://www.maestrocard.com" target="_blank">
                            <img src="<?php echo $this->getViewFileUrl('Leftor_PikPay::images/maestro.png') ?>" alt="Maestro" />
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="https://www.visa.com" target="_blank">
                            <img src="<?php echo $this->getViewFileUrl('Leftor_PikPay::images/verified_by_visa.jpg') ?>" alt="Verified by Visa" />
                        </a>
                    </td>
                    <td>
                        <a href="https://www.mastercard.com" target="_blank">
                            <img src="<?php echo $this->getViewFileUrl('Leftor_PikPay::images/mastercard-securecode.jpg') ?>" alt="Mastercard Securecode" />
                        </a>
                    </td>

                </tr>
                </tbody>
            </table>

        </div>
        <?php if($paymentType == 1): ?>
        <div class="col-xs-6">
            <p>Ako se nije desila automatska redirekcija, kliknite na dugme "Plati"</p>
        </div>
        <script>
            document.getElementById("redirectpay").submit();
        </script>
        <?php endif ?>
    </div>
</div>
